config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'users/index'
  get 'users/show'
  root 'posts#index'
  get 'users/:user_id/friendships', to: 'friendships#index'

  mount ActionCable.server => '/cable'

  resources :users do 
    resources :friendships , only: [:index, :show] do 
      member do 
        post :create_request
        put :accept_request
        put :decline_request
        delete :destroy
      end
    end
  end
   
  resources :posts do
    resources :comments do 
      resources :likes, only: [:create, :destroy]
    end  
    resources :likes, only: [:create, :destroy] 
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  namespace :api do 
    namespace :v1 do 
      resources :users, only: [:index, :show, :create, :update, :destroy]
    end
  end
  namespace :api do 
    namespace :v1 do 
      resources :posts, only: [:index]
    end
  end

  get "/posts/generate_pdf", to: "posts#generate_pdf"
  get '/data/download_csv', to: 'data#download_csv'
  get "/data/generate_pdf", to: "data#generate_pdf"



  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
end

  # resources :users do
  #   member do
  #     get :friends
  #     get :pending_friend_requests
  #     get :friend_requests_received
  #     post :accept_friendship
  #     post :decline_friendship
  #   end 
  # end
  
  # put 'users/:id/accept_friendship', to: 'users#accept_friendship', as: 'accept_friendship'
  # put 'users/:id/decline_friendship', to: 'users#decline_friendship', as: 'decline_friendship'
  # get 'users/pending_friend_requests', to: 'users#pending_friend_requests', as: 'pending_friend_requests'
  # get 'users/friend_requests_received', to: 'users#friend_requests_received', as: 'friend_requests_received'
  # get 'users/friends', to: 'users#friends', as: 'friends'

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true


  validates :user_id, uniqueness: {scope: [:likable_type, :likable_id]}                          #user can only likes once

  def self.increment_counter(likable_id)
    where(likable_id: likable_id).count
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @posts = Post.all.order(created_at: :desc)
    @likable = find_likable
    @like = find_likable.likes.build(user: current_user)

    if @like.save
      if @like.likable.is_a? Post
        respond_to do |format| 
          format.html {redirect_to posts_path, notice: 'You liked this POST'}
          format.js {render 'create.js.erb'}
        end
      else 
        @post = Post.find(params[:post_id])
        respond_to do |format| 
          format.html {redirect_to post_path(@post), notice: 'You liked this COMMENT'}
          format.js {render 'create_comment_like.js.erb'}
        end 
      end
    else 
      respond_to do |format| 
        format.html {redirect_to posts_path, notice: 'Sorry, something went wrong'}
        format.js
      end 
    end
  end

  def destroy
    @posts = Post.all.order(created_at: :desc)
    @likable = find_likable
    @like = find_likable.likes.find(params[:id])

    if @like.user == current_user && @like.destroy
      if @like.likable_type=="Post"
        respond_to do |format| 
          format.html {redirect_to posts_path, notice: 'You disliked this post'}
          format.js {render 'destroy.js.erb'}
        end
      else 
        @post = Post.find(params[:post_id])
        respond_to do |format| 
          format.html {redirect_to post_path(@post), notice: 'You disliked this COMMENT'}
          format.js {render 'destroy_comment_like.js.erb'}
        end 
      end
    else
      respond_to do |format| 
        format.html {redirect_to posts_path, alert: "Sorry, something went wrong. Please try again."}
        format.js 
      end
    end
  end

  private 

  def find_likable 
    if(params[:comment_id]).present?
      Comment.find(params[:comment_id])
    else 
      Post.find(params[:post_id])
    end  
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_showing_comment_likes.html.erb
<div class='show-comment-likes'>
    Likes: <%= Like.where(likable_type: "Comment", likable_id: comment.id).count%><br>
    <%if user_signed_in? && current_user.id!=@post.user.id && current_user.id!=comment.user.id%>
        <% like = Like.find_by(user_id: current_user.id, likable_type: "Comment", likable_id: comment.id)%>
        <%= like_button_comment(@post,comment)%>      
    <%end%>          
</div>

app/views/likes/_showing_likes.html.erb
<div class="show-likes">
  Likes: <%= Like.where(likable_id: post.id, likable_type: "Post").count %><br>
  <% if user_signed_in? && current_user.id != post.user.id %>
      <%= like_button_post(post)%>
  <% end %>
  <br>    
</div>

app/views/likes/_showing_posts.html.erb
<div class="show-posts">
    <% @posts.each do |post| %>
      <li>
        <p>
          <%= link_to "-> #{post.user.fname}", user_path(post.user), style: 'color:#2F4F4F'%>
          <br>
          <%= post.body%><br>
          <% if post.image.attached? %>
            <%= image_tag post.image %>
          <% end %>
          <% if user_signed_in? && current_user.id==post.user.id%> 
            <%= link_to 'Delete', post_path(post.id), method: :delete, data: {confirm: "Do you want to delete this post"},style: 'color:#E34234' %><br>
          <%end%> 
          <br>
          <div class="show-likes">
            Likes: <%= Like.where(likable_id: post.id, likable_type: "Post").count %><br>
              <% if user_signed_in? && current_user.id != post.user.id %>
                <% like = Like.find_by(user_id: current_user.id, likable_type: "Post", likable_id: post.id) %>
                <%if like.present?%>
                  <%= button_to post_like_path(like.likable_id, like.id, likable_type: "Post"), method: :delete, remote: true, style: 'color:#E34234' do%>
                    <span>&#128078;</span>
                  <%end%>  
                <%else%>
                  <%= button_to post_likes_path(post), method: :post,remote: true, style: 'color:#2E8B57' do%>
                    <span>&#128077;</span>
                  <%end%>  
                <%end%>
              <% end %>
          <%= link_to 'Comments', post, style: 'color:#A0522D'%>
          </div>  
        </p> 
      </li>
    <% end %>
  </div>

app/views/likes/create.js.erb
<% selector = ".show-likes.for-post-#{@likable.id}" %>

$("<%= selector %>").html("<%= escape_javascript(render('showing_likes', post: @likable))%>");

app/views/likes/create_comment_like.js.erb
<% selector = ".show-comment-likes.for-comment-#{@likable.id}" %>

$("<%= selector %>").html("<%= escape_javascript(render('showing_comment_likes', comment: @likable))%>");

app/views/likes/destroy.js.erb
<% selector = ".show-likes.for-post-#{@likable.id}" %>

$("<%= selector %>").html("<%= escape_javascript(render('showing_likes', post: @likable))%>");

app/views/likes/destroy_comment_like.js.erb
<% selector = ".show-comment-likes.for-comment-#{@likable.id}" %>

$("<%= selector %>").html("<%= escape_javascript(render('showing_comment_likes', comment: @likable))%>");