config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'users/index'
  get 'users/show'
  root 'posts#index'
  get 'users/:user_id/friendships', to: 'friendships#index'

  mount ActionCable.server => '/cable'

  resources :users do 
    resources :friendships , only: [:index, :show] do 
      member do 
        post :create_request
        put :accept_request
        put :decline_request
        delete :destroy
      end
    end
  end
   
  resources :posts do
    resources :comments do 
      resources :likes, only: [:create, :destroy]
    end  
    resources :likes, only: [:create, :destroy] 
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  namespace :api do 
    namespace :v1 do 
      resources :users, only: [:index, :show, :create, :update, :destroy]
    end
  end
  namespace :api do 
    namespace :v1 do 
      resources :posts, only: [:index]
    end
  end

  get "/posts/generate_pdf", to: "posts#generate_pdf"
  get '/data/download_csv', to: 'data#download_csv'
  get "/data/generate_pdf", to: "data#generate_pdf"



  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
end

  # resources :users do
  #   member do
  #     get :friends
  #     get :pending_friend_requests
  #     get :friend_requests_received
  #     post :accept_friendship
  #     post :decline_friendship
  #   end 
  # end
  
  # put 'users/:id/accept_friendship', to: 'users#accept_friendship', as: 'accept_friendship'
  # put 'users/:id/decline_friendship', to: 'users#decline_friendship', as: 'decline_friendship'
  # get 'users/pending_friend_requests', to: 'users#pending_friend_requests', as: 'pending_friend_requests'
  # get 'users/friend_requests_received', to: 'users#friend_requests_received', as: 'friend_requests_received'
  # get 'users/friends', to: 'users#friends', as: 'friends'

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

  validates :sender_id, uniqueness: { scope: :receiver_id }
  validate :receiver_cannot_send_request_to_friend

  def receiver_cannot_send_request_to_friend
    if Friendship.exists?(sender_id: sender_id, receiver_id: receiver_id, status: 'accepted') || 
      Friendship.exists?(sender_id: receiver_id, receiver_id: sender_id)
      errors.add(:receiver_id, "Receiver cannot send a friend request to someone who is already their friend.")
    end
  end

  enum status: [:pending, :accepted, :declined]
  
  scope :pending_requests, ->{where(status: :pending)}
  scope :accepted_requests, ->{where(status: :accepted)}
  scope :declined_requests, ->{where(status: :declined)}
  
  def self.friends_of(user)
    where(sender: user, status: :accepted).or(where(receiver: user, status: :accepted))
  end
end

# validate :unique_sender_receiver_ids
# validate :sender_send_one_request

# def unique_sender_receiver_ids
#   if Friendship.exists?(sender_id: receiver_id, receiver_id: sender_id)
#     errors.add(:sender_id, "Sender and Receiver IDs must be unique in both directions")
  #     errors.add(:receiver_id, "Sender and Receiver IDs must be unique in both directions")
  #   end
  # end
  
  # def sender_send_one_request
  #   if Friendship.exists?(sender_id: sender_id, receiver_id: receiver_id)
  #     errors.add(:sender_id, "Sender cant send friend request multiple times to same receiver")
  #   end
  # end
  
  # enum status: {
    #   pending :0,
    #   accepted :1,
    #   declined :2
    # }
    
    
    # def accept 
    #   self.update(status: :accepted)
    # end
    
    # def decline   
    #   self.update(status: :declined)
    # end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    
    def index 
        @users_except_me = User.where.not(id: current_user.id)
        @pending_requests = current_user.received_friend_requests.pending_requests
        @accepted_requests = current_user.sent_friend_requests.accepted_requests
        @declined_requests = current_user.sent_friend_requests.declined_requests
        # @suggested_users = User.find(params[:receiver_id])
        @friends_show = Friendship.friends_of(current_user) 
    end
    
    def show  
        @accepted_requests = current_user.sent_friend_requests.accepted_requests
        @suggested_user = User.find(params[:id])
    end

    def create_request
        @friends_show = Friendship.friends_of(current_user) 
        @suggested_user = User.find(params[:id])
        @friendship = current_user.sent_friend_requests.build(receiver_id: @suggested_user.id ,status: :pending)    
        if @friendship.save  
            respond_to do |format|
                format.html {redirect_to user_friendships_path, notice: "Friend request sent to #{@suggested_user.fname}"}
                format.js 
            end
        else
            respond_to do |format|
                format.html {redirect_to user_friendships_path, notice: "Error while sending friend request"}
                format.js 
            end
        end
    end

    def accept_request
        @friends_show = Friendship.friends_of(current_user) 
        @friendship = Friendship.find(params[:id])                     #retrieve existing record
        if @friendship.accepted! 
            respond_to do |format|
                format.html {redirect_to user_friendships_path, notice: "Friend request accepted"}
                format.js 
            end      
        else
            respond_to do |format|
                format.html {redirect_to user_friendships_path, notice: "Error while accepting friend request"}         #current_user 
                format.js 
            end
        end
    end

    def decline_request
        @friends_show = Friendship.friends_of(current_user)
        @friendship = Friendship.find(params[:id])
        if @friendship.declined!    
            # Enqueue the job to delete the friendship record in 10 minutes
            DeleteFriendshipJobJob.set(wait_until: 1.minutes.from_now).perform_later(@friendship.id)

            flash[:success] = 'Friend request declined'
        else
            flash[:error] = 'Error while declining friend request'
        end
        respond_to do |format|
            format.html {redirect_to user_friendships_path}
            format.js 
        end
    end
    
    def destroy 
        @friendship = Friendship.find(params[:id])
        @friendship.destroy
        flash[:notice] = 'Friend removed'
        redirect_to user_friendships_path
    end
    private
    
    def friendship_params
        params.require(:friendship).permit(:sender_id,:receiver_id,:status)
    end
    
    # def current_user
    #     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper

    def accepted_request(accepted_requests)
        @accepted_requests.each do |request| 
            link_to request.receiver.fname, request.receiver
        end
    end

    def declined_request(declined_requests)
        @declined_requests.each do |request|
            link_to request.receiver.fname, request.receiver
        end
    end

    def send_friends_request(users)
        @users.each do |user| 
            link_to user.fname, create_request_user_friendship_path(user.id, user_id: current_user), method: :post, remote: true 
        end 
    end

    def friends_show(fr)
        @fr.each do |f|
            if f.sender.fname==current_user.fname
                f.receiver.fname
                link_to 'Destroy friendship', user_friendship_path(current_user, f), method: :delete, data: { confirm: "Are you sure you want to unfriend #{f.receiver.fname}?" }, style: 'color:#CD5C5C'
            else
                f.sender.fname
                ink_to 'Destroy friendship', user_friendship_path(current_user, f), method: :delete, data: { confirm: "Are you sure you want to unfriend #{f.sender.fname}?" }, style: 'color:#CD5C5C'
            end
          end
    end
end

app/views/friendships/_friends_list.html.erb
<div class="show-friends">
  <% if @friends_show.any?%>  
    <h3>Friends</h3>
    <ul>
        <% @friends_show.each do |f|%>
        <li>
            <% if f.sender.fname==current_user.fname%>
            <%= f.receiver.fname%>
            <%else%>
            <%= f.sender.fname%>
            <%end%>
        </li>
        <%end%>  
    </ul>
  <%end%>  
</div>

app/views/friendships/_friendship_reqeust.html.erb
<li id="request-<%= friendship_request.id %>">
  <%= link_to friendship_request.sender.fname, friendship_request.sender %>
  <div class="friendship-request-actions">
    <% if friendship_request.pending? %>
      <%= link_to "Accept", accept_request_user_friendship_path(friendship_request.id, user_id: current_user), method: :put, remote: true, class: "accept-request-button", data: { request_id: friendship_request.id } %>
      <%= link_to "Decline", decline_request_user_friendship_path(friendship_request.id, user_id: current_user), method: :put, remote: true, class: "decline-request-button", data: { request_id: friendship_request.id } %>
    <% elsif friendship_request.accepted? %>
      <%= link_to "Unfriend", destroy_user_friendship_path(friendship_request.id, user_id: current_user), method: :delete, remote: true, class: "unfriend-button", data: { request_id: friendship_request.id } %>
    <% end %>
  </div>
</li>

app/views/friendships/accept_request.html.erb
<% if @friendship.accepted! %>
    <h1> Friend reqeust accepted </h1>
<%end%>

app/views/friendships/accept_request.js.erb
$(".pending-requests").hide();

alert("Friendship request accepted");

$(".show-friends").hide();

$('#friends-list').html("<%= escape_javascript(render('friends_list'))%>");         //alternative .append() which adds new content to existing content of an element
                                                                                    //.html() replaces existing content of an element with new content                                                                                            


<%# $.ajax({
  type: "GET",
  url: "/friends",
  dataType: "script",
  success: function(response) {
    $('#friends-list').empty().append(response);
  }
}); %>

app/views/friendships/create_request.html.erb
<h1> Sending Friend Request....</h1>


<h1>New Friendship Request</h1>

<%= form_with model: [@friendship.sender, @friendship], url: create_request_user_friendship_path do |f| %>
  <%= hidden_field_tag :receiver_id, @friendship.receiver_id %>

  <%= f.submit "Send Request"%>

<% end %>

<p> Your friend request has been sent </p>

app/views/friendships/create_request.js.erb
<% if @friendship.save %>
    alert("Friendship request sent!");
<%end%>

app/views/friendships/decline_request.html.erb
<% if @friendship.declined! %>
    <h1> Friend request declined </h1>
<% end%>

app/views/friendships/decline_request.js.erb
$(".pending-requests").hide();

alert("Friendship request declined!!");

$(".show-friends").hide();

$('#friends-list').html("<%= escape_javascript(render partial: 'friends_list') %>");

app/views/friendships/destroy.html.erb
<h1>Friend removed</h1>

<p>You have successfully removed this friend from your list.</p>

app/views/friendships/index.html.erb
<%= "Logged in as #{current_user.fname}"%><br>

<h1>Friendship Requests</h1><br>
<div class="friendship-requests">

  <div class="pending-requests">
    <% if @pending_requests.any? %>
      <h3>Pending Requests</h3>
    
      <ul>
        <% @pending_requests.each do |request| %>
          <li id="friend-request- <%= request.id %>">
            <%= link_to request.sender.fname, request.sender, style: 'color:#4682B4' %>
            <br>
            <%= link_to "Accept", accept_request_user_friendship_path(request.id, user_id: current_user), class: "accept-button", method: :put, remote: true, style: 'color:#006400' %>
            <br>
            <%= link_to "Decline", decline_request_user_friendship_path(request.id, user_id: current_user), class: "decline-button", method: :put, remote: true, style: 'color:#CD5C5C' %>
          </li>
        <% end %>
      </ul>
      <% end %>
  </div>

  <div class="accepted-requests">
    <% if @accepted_requests.any? %>
      <h3>Sent and Accepted Requests</h3>

      <ul>
        <% @accepted_requests.each do |request| %>
          <li>
            <%= link_to request.receiver.fname, request.receiver %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="declined-requests">
    <% if @declined_requests.any? %>
      <h3>Declined Requests By</h3>

      <ul>
        <% @declined_requests.each do |request| %>
          <li>
            <%= link_to request.receiver.fname, request.receiver %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="send-requests">
    <h1>Send request to:-</h1>

    <ul>
      <% @users_except_me.each do |user| %>
        <li>
          <%= link_to user.fname, create_request_user_friendship_path(user.id, user_id: current_user), method: :post, remote: true %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="show-friends">
  <h3>Friends</h3>
  <ul>
    <% @friends_show.each do |f|%>
      <li>
        <% if f.sender.fname==current_user.fname%>
          <%= f.receiver.fname%>
          <%= link_to 'Destroy friendship', user_friendship_path(current_user, f), method: :delete, data: { confirm: "Do you want to unfriend #{f.receiver.fname}?" }, style: 'color:#CD5C5C'%>
        <%else%>
          <%= f.sender.fname%>
          <%= link_to 'Destroy friendship', user_friendship_path(current_user, f), method: :delete, data: { confirm: "Do you want to unfriend #{f.sender.fname}?" }, style: 'color:#CD5C5C'%>
        <%end%>
      </li>
    <%end%>  
  </ul>
</div>

<div id="friends-list"></div>

<%= render_flash_messages %>  

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign iin", new_user_session_path %>
<% end %>

app/views/friendships/new.html.erb
<h1>New Friendship Request</h1>

<%= form_with model: [@friendship.sender, @friendship], url: friendships_path do |f| %>
  <%= hidden_field_tag :receiver_id, @friendship.receiver_id %>

  <%= f.submit "Send Request", class: "btn btn-primary" %>
<% end %>

app/views/friendships/show.html.erb
<%= link_to 'Sending', create_request_user_friendship_path(@suggested_user.id, user_id: current_user), method: :post %>