config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'users/index'
  get 'users/show'
  root 'posts#index'
  get 'users/:user_id/friendships', to: 'friendships#index'

  mount ActionCable.server => '/cable'

  resources :users do 
    resources :friendships , only: [:index, :show] do 
      member do 
        post :create_request
        put :accept_request
        put :decline_request
        delete :destroy
      end
    end
  end
   
  resources :posts do
    resources :comments do 
      resources :likes, only: [:create, :destroy]
    end  
    resources :likes, only: [:create, :destroy] 
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  namespace :api do 
    namespace :v1 do 
      resources :users, only: [:index, :show, :create, :update, :destroy]
    end
  end
  namespace :api do 
    namespace :v1 do 
      resources :posts, only: [:index]
    end
  end

  get "/posts/generate_pdf", to: "posts#generate_pdf"
  get '/data/download_csv', to: 'data#download_csv'
  get "/data/generate_pdf", to: "data#generate_pdf"



  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
end

  # resources :users do
  #   member do
  #     get :friends
  #     get :pending_friend_requests
  #     get :friend_requests_received
  #     post :accept_friendship
  #     post :decline_friendship
  #   end 
  # end
  
  # put 'users/:id/accept_friendship', to: 'users#accept_friendship', as: 'accept_friendship'
  # put 'users/:id/decline_friendship', to: 'users#decline_friendship', as: 'decline_friendship'
  # get 'users/pending_friend_requests', to: 'users#pending_friend_requests', as: 'pending_friend_requests'
  # get 'users/friend_requests_received', to: 'users#friend_requests_received', as: 'friend_requests_received'
  # get 'users/friends', to: 'users#friends', as: 'friends'

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
  has_one_attached :image

  validates :body, presence: true, length: {maximum: 300}

  # def self.search(q)
  #   if q
  #     where('body LIKE ?', "%#{q}%") 
  #   else
  #     all
  #   end
  # end
  scope :searching, ->(query) {where("body LIKE ?", "%#{query}%")}

end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
      class PostsController<ApplicationController
          skip_before_action :authenticate_user!
          skip_before_action :verify_authenticity_token
            
          def index 
            @posts = Post.order(created_at: :desc).paginate(page: params[:page], per_page: 5)

            render json: {data: ActiveModelSerializers::SerializableResource.new(@posts, each_serializer: PostSerializer), 
              meta: {
                total_pages: @posts.total_pages,
                current_page: @posts.current_page
            }}

            # render json: {posts: @posts, total_pages: @posts.total_pages, current_page: @posts.current_page}  

          end
      end
  end
end

# NOTE: ActiveModel::SerializableResource.new is deprecated; use ActiveModelSerializers::SerializableResource. instead

            

            

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!
  # protect_from_forgery except: :index

  def index
    @posts = Post.all.searching(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    # @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    # render json: {posts: @posts}
    respond_to do |format|
      format.html
      format.js
    end
    # respond_to do |format|
    #   format.pdf do 
    #     pdf = Prawn::Document.new
    #     pdf.text "PDF generation"
    
    #     send_data pdf.render, filename: "document.pdf", type: "application/pdf", disposition: "inline"
    #   end
    # end

  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    render json: {post: @post}
    # @comment = Comment.new
  end

  def new
    @post = Post.new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    authorize @post                       #pundit
    # authorize! :create, @post               #cancancan

    if @post.save
      flash[:notice] = "Post was successfully created"
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy 
    @post = current_user.posts.find(params[:id])
    # unless @post.editable_by?(current_user)
    #   redirect_to @post, alert: "You are not authorized to delete this post."
    # end
    authorize @post
    @post.destroy
    flash[:notice] = "Post was successfult deleted"
    redirect_to root_path
  end

  # def generate_pdf
  #   respond_to do |format|
  #     format.pdf do 
  #       pdf = Prawn::Document.new
  #       pdf.text "PDF generation"
    
  #       send_data pdf.render, filename: "document.pdf", type: "application/pdf", disposition: "inline"
  #     end
  #   end
  # end


  private 

  def post_params
    params.require(:post).permit(:body, :image)
  end

  #for edit, update, destroy
  def authorize_user
    redirect_to root_path, alert: 'You are not authorized to perform this action.' unless current_user == @post.user
  end
    
end

app/helpers/posts_helper.rb
module PostsHelper

    def post_author(post)
        "=>> #{post.user.fname}"
    end

    def delete_post(post)
        link_to 'Delete', post_path(post.id), method: :delete, data: {confirm: "Do you want to delete this post"},style: 'color:#E34234'
    end

    def like_button_post(post)
        like = Like.find_by(user_id: current_user.id, likable_type: "Post", likable_id: post.id)
        if like.present?
            button_to post_like_path(like.likable_id, like.id, likable_type: "Post"), method: :delete, remote: true, style: 'color:#E34234' do
                content_tag(:span, '👎')
            end
        else
            button_to post_likes_path(post), method: :post,remote: true, style: 'color:#2E8B57' do
                content_tag(:span, '👍')
            end
        end
    end

    def post_author(comment)
        "-> #{comment.user.fname}"
    end

    def delete_comment(post,comment)
        link_to 'delete', post_comment_path(@post,comment), method: :delete, data: {confirm: "Do you want to delete this comment"}, style: 'color:#E34234'
    end

    def like_button_comment(post,comment)
        like = Like.find_by(user_id: current_user.id, likable_type: "Comment", likable_id: comment.id)
        if like.present?
            button_to post_comment_like_path(@post.id,like.likable_id,like.id,likable_type: "Comment"), method: :delete, remote:true, style: 'color:#E34234' do
                content_tag(:span, '👎')
            end
        else
            button_to post_comment_likes_path(@post.id,comment.id), method: :post, remote:true, style: 'color:#2E8B57' do
                content_tag(:span, '👍')
            end
        end
    end

end

app/views/posts/_form.html.erb
<%= form_for @post do |form|%>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <div class="field">
    <%= form.label :body %><br>
    <%= form.text_area :body,class: "form-control" %><br>
  </div>

  <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image,class: "form-control" %><br>
  </div>

  <div class="actions"><br>
    <%= form.submit "Add Post", class: 'btn btn-outline-success'%>
  </div>
  </div>
<% end %>

app/views/posts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'FRIENDBOOK', users_index_path, class: "navbar-brand"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%# <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> %>

      <% if user_signed_in?%>
        <li class="nav-item">
            <%= link_to "Posts", posts_path, class: "nav-link"%>
        <li class="nav-item">
            <%= link_to "Add posts", new_post_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Chats", conversations_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Edit Profile",edit_user_registration_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Sign Out",destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li> 
      <% else%>
        <form class="form-inline my-2 my-lg-0"> 
        <li class="nav-item">
            <%= link_to "Sign In",new_user_session_path, class: "nav-link"%>
        </li> 

        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
        </li> 
        </form>

      <%end%>

      

      <%# <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> %>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0"> %>
      <%# <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> %>
      <%# <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> %>
    <%# </form> %>
  </div>
</nav>

app/views/posts/_posts.html.erb
<div class="show-posts">
  <% @posts.each do |post| %>
    <li>
      <p>
        <%= link_to "-> #{post.user.fname}", user_path(post.user), style: 'color:#2F4F4F'%>
        <br>
        <%= post.body%><br>
        <% if post.image.attached? %>
          <%= link_to image_tag(post.image), url_for(post.image), target: '_blank' %>
        <% end %>
        <% if user_signed_in? && current_user.id==post.user.id%> 
          <%= delete_post(post) %><br>
        <%end%> 
        <div class="show-likes for-post-<%=post.id%>">
          Likes: <%= Like.where(likable_id: post.id, likable_type: "Post").count %><br>
            <% if user_signed_in? && current_user.id != post.user.id %>
              <%= like_button_post(post)%>
            <% end %>
        <br>    
        </div>  
        <%= link_to 'Comments', post, style: 'color:#A0522D'%>
      </p> 
    </li>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= "Logged in as #{current_user.fname}"%><br><br>

<h1>All Posts</h1>
<%= form_tag posts_path, :method => 'get', :id => "postsSearch", remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil,class: 'btn btn-outline-success' %>
  </p>
<%end%>  

<ul>
  <div class="show-posts">
    <% @posts.each do |post| %>
      <li>
        <p>
          <%= link_to "-> #{post.user.fname}", user_path(post.user), style: 'color:#2F4F4F'%>
          <br>
          <%= post.body%><br>
          <% if post.image.attached? %>
            <%= link_to image_tag(post.image), url_for(post.image), target: '_blank' %>
          <% end %>
          <% if user_signed_in? && current_user.id==post.user.id%> 
            <%= delete_post(post) %><br>
          <%end%> 
          <div class="show-likes for-post-<%=post.id%>">
            Likes: <%= Like.where(likable_id: post.id, likable_type: "Post").count %><br>
              <% if user_signed_in? && current_user.id != post.user.id %>
                <%= like_button_post(post)%>
              <% end %>
          <br>    
          </div>  
          <%= link_to 'Comments', post, style: 'color:#A0522D'%>
        </p> 
      </li>
    <% end %>
  </div>
</ul>

<%# <div id="showing-posts"></div> %>

<%= link_to "New Post", new_post_path, style: 'color:0000FF' %>

<br><br>
<div id="infinite-scrolling">
  <%= will_paginate @posts %>
</div>

app/views/posts/index.js.erb
<%if params[:page].present?%>

  $('.show-posts').append('<%= j render('posts') %>');
  <% if @posts.next_page %>
  
    $('.pagination').replaceWith('<%= j will_paginate('posts') %>');
  <% else %>
    $(window).off('scroll');
    $('.pagination').remove();
  <% end %>

<%else%>

  $('.show-posts').html('<%= j render('posts') %>');

<%end%>  

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<br>

<%= render 'posts/form', post:@post%>

app/views/posts/show.html.erb
<h2>POST :-</h2>
<br>
<p> 
    <%= @post.body%> 
</p>

<h4>Comments</h4> <br>
<% @post.comments.each do |comment|%>
    <p>
    <%= post_author(comment)%> <br>
    <%= comment.content %> 
    <%if current_user.id==comment.user.id%>
        <%= delete_comment(@post,comment) %> 
    <%end%>
    <div class='show-comment-likes for-comment-<%=comment.id%>'>
        Likes: <%= Like.where(likable_type: "Comment", likable_id: comment.id).count%><br>
        <%if user_signed_in? && current_user.id!=@post.user.id && current_user.id!=comment.user.id%>
            <% like = Like.find_by(user_id: current_user.id, likable_type: "Comment", likable_id: comment.id)%>
            <%= like_button_comment(@post,comment)%>      
        <%end%>          
    </div>
    </p> 
<%end%>

<%if current_user.id!=@post.user.id%>
    <h5>Add comments</h5><br>
    <%= render 'comments/form', post:@post%>
<%end%>

                           